### ISSUE TITLE
Upgrade items not working

### ISSUE THREAD

**Issue by TheRedBull** [TheRedBull/ConfirmSP#10]
You cannot use this addon to auto-click 'yes' when trying to upgrade an item

**Comment by Texxer** [comment]
Sad... why is that?!

**Comment by TheRedBull** [comment]
Best I can tell... API changes put the second confirmation behind a different call so this feature may stay broken... I'll keep digging as I have time unless someone else gets to it first...

**Comment by TheRedBull** [comment]
Actually, looking deeper into the dev logs... it looks like the 2nd confirmation is now a protected function... this will be blacklisted in the next push
