### ISSUE TITLE
patch 11.0.2 finally broke it

### ISSUE THREAD

**Issue by zalidthebur** [TheRedBull/ConfirmSP#11]
Sadly the latest patch broke this excellent addon.
I doubt it will now be fixed and will be put to rest.
I will miss you for making my game life so much easier.
RIP ConfirmSP.

Just on the way off chance that someone can fix it.
Here are the errors:

7x ConfirmSP/csp-private.lua:5: GetAddOnMetadata
[string "=[C]"]: in function `assert'
[string "@ConfirmSP/csp-private.lua"]:5: in main chunk

Locals:
(*temporary) = false
(*temporary) = "GetAddOnMetadata"

**Comment by zalidthebur** [comment]
7x ConfirmSP/csp-profile.lua:155: attempt to index field 'L' (a nil value)
[string "@ConfirmSP/csp-profile.lua"]:155: in function `OptionsLoad'
[string "@ConfirmSP/csp-core.lua"]:22: in function <ConfirmSP/csp-core.lua:19>
[string "=[C]"]: ?
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@BattlePetCompletionist/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ePetCompletionist/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "ConfirmSP"
 orderedModules = <table> {
 }
 DB = <table> {
 }
 AceDB = <table> {
 }
 baseName = "ConfirmSP"
 private = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
(*temporary) = <table> {
 type = "group"
}
(*temporary) = <table> {
 ver = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'L' (a nil value)"
P = <table> {
}
CSP = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "ConfirmSP"
 orderedModules = <table> {
 }
 DB = <table> {
 }
 AceDB = <table> {
 }
 baseName = "ConfirmSP"
 private = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
LibStub = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
ADDON = "ConfirmSP"

**Comment by zalidthebur** [comment]
7x ConfirmSP/csp-events.lua:12: attempt to concatenate field 'VERSION' (a nil value)
[string "@ConfirmSP/csp-events.lua"]:12: in function `?'
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@AskMrRobot/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <AskMrRobot/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "ConfirmSP"
 orderedModules = <table> {
 }
 DB = <table> {
 }
 AceDB = <table> {
 }
 baseName = "ConfirmSP"
 private = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
(*temporary) = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "ConfirmSP"
 orderedModules = <table> {
 }
 DB = <table> {
 }
 AceDB = <table> {
 }
 baseName = "ConfirmSP"
 private = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
(*temporary) = "|cFFFF0000"
(*temporary) = nil
(*temporary) = " "
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'VERSION' (a nil value)"
P = <table> {
}

**Comment by artazika** [comment]
53x ConfirmSP/csp-profile.lua:152: attempt to index field 'L' (a nil value)
[string "@ConfirmSP/csp-profile.lua"]:152: in function `OptionsLoad'
[string "@ConfirmSP/csp-core.lua"]:22: in function <ConfirmSP/csp-core.lua:19>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "ConfirmSP"
 orderedModules = <table> {
 }
 DB = <table> {
 }
 AceDB = <table> {
 }
 baseName = "ConfirmSP"
 private = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
(*temporary) = <table> {
 type = "group"
}
(*temporary) = <table> {
 ver = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'L' (a nil value)"
P = <table> {
}
CSP = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "ConfirmSP"
 orderedModules = <table> {
 }
 DB = <table> {
 }
 AceDB = <table> {
 }
 baseName = "ConfirmSP"
 private = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
LibStub = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
ADDON = "ConfirmSP"

**Comment by Yanngo** [comment]
Since the latest patch a number of addons have been broken. And the same fix applies to a number of these addons:
**replace GetAddOnMetadata with C_AddOns.GetAddOnMetadata.**
So I went and replaced some in csp-private.lua

In particular, line 5 now looks like this:
`local GetAddOnMetadata = _G.C_AddOns.GetAddOnMetadata; assert(C_AddOns.GetAddOnMetadata ~= nil,'C_AddOns.GetAddOnMetadata')`
And line 9 looks like this:
`P.VERSION = (C_AddOns.GetAddOnMetadata(ADDON, "Version") or "") .. " " .. (C_AddOns.GetAddOnMetadata(ADDON, "X-Date") or "")`
I will attach a file for those who don't want to edit. 
[ConfirmSP.zip](https://github.com/user-attachments/files/16648010/ConfirmSP.zip)
The addon works for me now.

**Comment by TheRedBull** [comment]
Sorry guys! Been sick :(

Got this patched for those who want to still use it and thank you @Yanngo for doing all the leg work :)

**Comment by artazika** [comment]
> Sorry guys! Been sick :(
> 
> Got this patched for those who want to still use it and thank you @Yanngo for doing all the leg work :)

Get well!
I realized that I had too many things automated and started to feel less comfortable without it. It would be sad to lose it. Thanks for supporting the addon!

**Comment by TheRedBull** [comment]
@artazika @zalidthebur @Yanngo @BrandonScoggins44 Sorry for the spam but I wanted to let you all know this is now back on CurseForge! :) https://www.curseforge.com/wow/addons/confirm-static-popups
