### ISSUE TITLE
Missing upload on Curseforge

### ISSUE THREAD

**Issue by Taizunz** [TheRedBull/ConfirmSP#13]
Hey, thanks for maintaining this.
Just wanna make sure you're aware that you forgot to upload the file on Curseforge.

**Comment by TheRedBull** [comment]
Thanks!

I'm still trying to learn my way around their ecosystem - I think I've got it (and a new update) in process so *fingerscrossed* I got it right this time

**Comment by TheRedBull** [comment]
Resolved; properly showing on the web search and the desktop app(s)
